# Generated by Django 4.2.2 on 2023-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
    ]
