# Generated by Django 4.2.2 on 2023-07-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_comment_product_alter_comment_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_replay',
            new_name='is_reply',
        ),
    ]
